version: '3'
services:
  jrc-en-model:
    image: librairy/jrc-en-model:1.3
    container_name: jrc-en-model
    ports:
     - "8085:7777"
    env_file:
      - model.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "jrc-en-log"
  jrc-es-model:
    image: librairy/jrc-es-model:1.3
    container_name: jrc-es-model
    ports:
     - "8086:7777"
    env_file:
      - model.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "jrc-es-log"
  jrc-fr-model:
    image: librairy/jrc-fr-model:1.3
    container_name: jrc-fr-model
    ports:
     - "8087:7777"
    env_file:
      - model.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "jrc-fr-log"
  jrc-it-model:
    image: librairy/jrc-it-model:1.3
    container_name: jrc-it-model
    ports:
     - "8088:7777"
    env_file:
      - model.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "jrc-it-log"
  jrc-pt-model:
    image: librairy/jrc-pt-model:1.3
    container_name: jrc-pt-model
    ports:
     - "8089:7777"
    env_file:
      - model.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "jrc-pt-log"
  solr:
    image: solr:7.7
    container_name: solr
    ports:
     - "8983:8983"
    volumes:
      - ./data/cores:/opt/solr/server/solr/mycores
      - ./data/banana:/opt/solr/server/solr-webapp/webapp/banana
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - documents
    env_file:
      - solr.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "solr-log"
  librairy:
    image: librairy/api:2.1.29
    container_name: librairy
    ports:
     - "8081:7777"
    env_file:
     - librairy.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "librairy-log"
  search-api:
    image: librairy/search-api:1.2.5
    container_name: search-api
    ports:
     - "8080:7777"
    env_file:
     - search.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "search-log"
  kg-api:
    image: tbfy/kg-api:0.3
    container_name: kg-api
    ports:
     - "8082:7777"
    env_file:
     - kg.env
    depends_on:
     - fuseki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "search-log"
  fuseki:
    image: stain/jena-fuseki:3.13.1
    container_name: fuseki
    ports:
      - "3030:3030"
    volumes:
      - ./data/fuseki:/fuseki
    env_file:
      - fuseki.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "fuseki-log"
  yasgui:
    image: erikap/yasgui
    container_name: yasgui
    ports:
      - "3040:80"
    env_file:
      - yasgui.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "yasgui-log"
  gateway:
    image: kong:0.13.0
    container_name: gateway
    container_name: gateway
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
    env_file:
      - gateway.env
    depends_on:
      - kg-gateway
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "gateway-log"
  kg-gateway:
    image: tbfy/kg-gateway:latest
    container_name: kg-gateway
    env_file:
      - gateway-db.env
    depends_on:
      - kg-api
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always
    stdin_open: false
    tty: false
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "kg-gateway-log"
